using System;

namespace PurrNet
{
    /// <summary>
    /// Assembly-level attribute used by PurrNet's IL post-processor to identify types
    /// whose methods should be prepared for NetworkReflection RPC dispatch.
    /// Auto-generated by the NetworkReflection inspector. Do not use manually.
    /// </summary>
    [AttributeUsage(AttributeTargets.Assembly, AllowMultiple = true)]
    public class ReflectionRPCTargetAttribute : Attribute
    {
        public Type TargetType { get; }

        public ReflectionRPCTargetAttribute(Type targetType)
        {
            TargetType = targetType;
        }
    }
}
